/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

import sumEvenFibonacci, {
  generateFibonacciSeriesWithRecursion,
  sumEvenNumbersArray,
} from '../problems/fibonacchi-even-sum';
import evenSumOfFibonacci from '../problems/fibonacchi-even-sum';
describe('check fibonacchi even sum', () => {
  it('should fail if sequence is more than 4000000 fast', () => {
    expect(evenSumOfFibonacci(4000000)).toBe(4613732);
  });
  it('should fail if sequence is more than 4000000 recursion', () => {
    expect(
      sumEvenNumbersArray(generateFibonacciSeriesWithRecursion(4000000))
    ).toBe(4613732);
  });
});
